server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.230.1:3306/service-passenger-user?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: yxym
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.230.1:8848
  application:
    name: service-passenger-user