server:
  port: 9001

alipay:
  appId: 2021000121697741
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCv24t3SxlJt480KvgP++B2572/YSBUc5XSUWHBe1xMPE4v++CtzGzrMqTEXVCfEpP4s73DWJIOzICixZP2R66WBI1ueToMnz/3VQW64jCMpse3ckk/sX9MRsgjWwr4754SiYmu3l6sFuT7RL1oMUAuUCDkPzySfnXXOqBveaJ/SlsyHYfVkL6xf2VZZvxyCZ1FStss7yYSY2iiLCyGUKYfxMY7/QXxBXiBXI6GaUlzCgAj+v7w/L/1Loi/GFT8d4ZFcrqsxS12x7go6Zx8CUHWuCNicwZakO5HDyen65JXtWe44yGdQ+kJXaoPkAUs01Y7GFtQOw38ceZN+/ezPfzFAgMBAAECggEAH21cvzTsj//915TWQAUDWDyR7GGvJWiCndNtZOZm2DjuwCSDQowF6wJh77W9crAfQZLdlst9Tqe9VVl518l3qdembte7SAYtqEXJgFxr0Lb9egsyi+9skHUVzzu1+kbYOPfbYyTaRmbRBRaDwtsKXTx0pFWovYVcCdqwUTurjpOu4LK5i2CoJtOrrHAASjfEb6YQxYxcLop23Yv3F4TucMnkqWYr3oFp3EAfR51MwkhkncLRKeg5F9SETr8w8LjuiVE6er+kD8G7KNrkgfC9Q1oE0k3oVinjYs8dx+mgF/q4y6SqdIaVkj/qm8AtfsD9ueKayJyvik7L+BvyhzOtAQKBgQDuJO93wk8aw+NvpR5Zx3HqPoXg4rR17chs40ogPLKKo3+Vqc31+CvTtiCgNSLx7jEtgLDqiHeEGIDYkGrhXWDKtSzSR1stR+93DOviwfv0duG5+i+5kJu/r0pKJqftQdpA/2JBwu04lwAUJ8gIJSNWqNjZHatzxqR2FII8uePTBwKBgQC9CwvqWKEJ4oJgBNDAK3c0Q2RxpIV95M9TAJHb8vjn81hOOdDe6Hjvr7y6Y4kLSaFqSOW7TK/VvZrjK82iIxHaSlU2eSCVh4x5iJ+05lpCcYOylJ5YlzLf+fzPAzNh5xsiY4avvUng3Zya5XJz9eJvmIky6gEV3E8MwEwIi2cC0wKBgQDKktixArTPi7o4CjkbHbElFTJE7hOcDTzkgyNW8Mrfa9znrp3okcaWPOLb5Ndo/LkQf9v+ZT9lOoK/tXl1Yz0msZ8C8Hf6uKpWlsNBDMoKVeYFkXBvZTdXgwCqut81z0Kc76DhV7L65FfIzV42r4C0AsUTS03BGkRjvWZbybSmmQKBgQCQjV7aHlVdmp94zpXVLCdlhlbK8zPEVW8XF+twlXUw4AnZHyqRGJBJL0cP+0ZypCXSgNVyCCy4Mti59uexoEFpesd39N0umcyXrhn5GN9RyT0cE7qVIWCclapznQ3wQeikvhfiT8qrMKosY2DGPPGdxbS7guW7ko+7v1skeXwWUwKBgQCEDkL2ychMqqCc8NiFpoyCecaH5p/2Hr7GDOIppayYVsA49WpoQARP2/eXZFhF7bVuc4gccSrmU3IzxutHyltYUqA+A3+njLKoA7mOqvbSrwIym2aZ32UFfFCHrs+L+jVyIPSvEmDHRv1K+5JlgYDsit06eiOquwlDRMWJF8VwqQ==
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv11CPri2nI/plLNaXNgr1ziQc/w++Zkb1cRDE+iUVkG/4yN2tomxAKtbpmrumxSqkkTxBainQLf0I9N8N17P5/MvaAYLchj9v2XbicyqQaVqd7OeNbXr0ythA61hu6KN5l9HJcvadREONRsr05++fXzZFy7IY0/EF9lU/1BhcKZypmUNR078XiK6c6kmLsDI8Znxu2UGJWcGtSaFx1bTOO37e7k8BFdWI4m8WvvaUSHDM97+uW/gU3FfsIJWYI/wVS/y0LuD6WYdNXBTeWI7TN3XMk6JKHuXldBx79UzBj1JnKxC3e7YQrgdIdGPNMDO0iw4wsCJM6wyJhGNCDnR0wIDAQAB
  notifyUrl: 65fb390020.goho.co/test



spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: service-pay